export const PROFILE_POSTS = [
  {
    id: "1",
    thumbnailUri: "https://picsum.photos/seed/ironman/400",
    isVideo: true,
    views: "8",
    description: "This is why I never skip a Wiz stream",
    date: "29 June",
  },
  {
    id: "2",
    thumbnailUri: "https://picsum.photos/seed/workout1/400",
    isVideo: true,
    views: "10",
    description: "Can we just stop all the weird",
    date: "3 July",
  },
  {
    id: "3",
    thumbnailUri: "https://picsum.photos/seed/fitness/400",
    isVideo: true,
    views: "10",
    description: "They didn't see the vision",
    date: "4 July",
  },
  {
    id: "4",
    thumbnailUri: "https://picsum.photos/seed/gym1/400",
    isVideo: true,
    views: "11",
    description: "Another one for the books",
    date: "5 July",
  },
  {
    id: "5",
    thumbnailUri: "https://picsum.photos/seed/exercise/400",
    isVideo: true,
    views: "10",
    description: "Keep the pace, keep the focus",
    date: "6 July",
  },
  {
    id: "6",
    thumbnailUri: "https://picsum.photos/seed/training/400",
    isVideo: true,
    views: "5",
    description: "Just another training day",
    date: "7 July",
  },
  {
    id: "7",
    thumbnailUri: "https://picsum.photos/seed/muscle/400",
    isVideo: true,
    views: "9",
    description: "Progress looks like this",
    date: "8 July",
  },
  {
    id: "8",
    thumbnailUri: "https://picsum.photos/seed/strength/400",
    isVideo: true,
    views: "7",
    description: "Stronger than yesterday",
    date: "9 July",
  },
  {
    id: "9",
    thumbnailUri: "https://picsum.photos/seed/power/400",
    isVideo: true,
    views: "12",
    description: "Power mode on",
    date: "10 July",
  },
  {
    id: "10",
    thumbnailUri: "https://picsum.photos/seed/athlete/400",
    isVideo: true,
    views: "6",
    description: "Keep it moving",
    date: "11 July",
  },
  {
    id: "11",
    thumbnailUri: "https://picsum.photos/seed/sport/400",
    isVideo: true,
    views: "4",
    description: "Game day energy",
    date: "12 July",
  },
  {
    id: "12",
    thumbnailUri: "https://picsum.photos/seed/pushup/400",
    isVideo: true,
    views: "9",
    description: "No days off",
    date: "13 July",
  },
];
